force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Install_Date__c</fullName>
    <description>DateTime Package was Installed</description>
    <label>Install Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Subscriber_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Subscriber_Version_Id__c</fullName>
    <label>Package Installed Subscriber Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Version_Number__c</fullName>
    <label>Package Installed Version Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Name__c</fullName>
    <description>Name of the Package. Can be sourced by sfdx-project.json or tooling api.</description>
    <label>Package Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueueGetInstalledPackagesTest.cls
@isTest
public with sharing class QueueGetInstalledPackagesTest {
    public static final DateTime CURRENT_PACKAGE_VERSION_INSTALL_DATETIME = (DateTime)Json.deserialize('2020-08-27T19:26:30.000Z', DateTime.class);
    public static final DateTime PREVIOUS_PACKAGE_VERSION_INSTALL_DATETIME = (DateTime)Json.deserialize('2019-08-27T19:26:30.000Z', DateTime.class);

    @testSetup 
    static void setup() {

    }
    
    static testmethod void testJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 

        QueueGetInstalledPackages queueGetInstalledPackagesJob = new QueueGetInstalledPackages();
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueGetInstalledPackagesJob);
        QueueGetInstalledPackages.doLater(queueGetInstalledPackagesJob.GetJobInfo());
        Test.stopTest(); 
        
        
        List<Demo_Component__C> demoComponents = [SELECT Id FROM Demo_Component__c];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals(16, demoComponents.size());
        System.assertEquals(jobId, jobInfo.Id);
        System.assertEquals(QueuePlatformAsyncEventHelper.STAGE_COMPLETED, queueGetInstalledPackagesJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_CURRENT_JOB_STAGE));
    }


    static testmethod void testChildJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 


        String ParentJobId = QueuePlatformAsyncEventHelper.generateId();
        QueueGetInstalledPackages queueGetInstalledPackagesJob = new QueueGetInstalledPackages(ParentJobId);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueGetInstalledPackagesJob);
        Test.stopTest(); 
        
        System.assertEquals(ParentJobId, queueGetInstalledPackagesJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID));
    }

    static testmethod void testHasExistingJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 
        
        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = null,
            SFDX_Package_Enabled_Flag__c=false,
            Source_Install_Type_Flag__c=false,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Demo Cleanup',
            Package_Name__c = 'Demo Cleanup',
            Subscriber_Package_Id__c = '0332E000000GTe7QAG',
            Latest_Package_Version_Name__c = 'Version 1.1.',
            Latest_Package_Version__c = '1.1.5-1',
            Latest_Subscriber_Package_Version_Id__c = '04t2E000003oc9rQAA',
            Installed__c = false,
            Last_Fetched__c = datetime.now(),
            Update_Available__c = false
        );
        insert demoComponent;

        Id demoComponentId = demoComponent.Id;
        QueueGetInstalledPackages queueGetInstalledPackagesJob = new QueueGetInstalledPackages();
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueGetInstalledPackagesJob);
        QueueGetInstalledPackages.doLater(queueGetInstalledPackagesJob.GetJobInfo());
        Test.stopTest(); 
 
        Demo_Component__C updatedDemoComponent = [SELECT Id, Update_Available__c, Installed__c, Package_Installed_Version_Number__c, Package_Installed_Subscriber_Version_Id__c FROM Demo_Component__c where Id = :demoComponentId LIMIT 1];
       

        System.assertEquals(true, updatedDemoComponent.Installed__c);
    }    


    static testmethod void testUpdatedComponentJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 
        
        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = null,
            SFDX_Package_Enabled_Flag__c=false,
            Source_Install_Type_Flag__c=false,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Demo Cleanup',
            Package_Name__c = 'Demo Cleanup',
            Subscriber_Package_Id__c = '0332E000000GTe7QAG',
            Latest_Package_Version_Name__c = 'Version 1.0.',
            Latest_Package_Version__c = '1.0.5-1',
            Latest_Subscriber_Package_Version_Id__c = '04t2E000003oc9rQAA',
            Package_Installed_Subscriber_Version_Id__c = ApiCalloutMock.PREVIOUS_SUBSCRIBER_PACKAGE_VERSION_ID,
            Installed_Version_Tracking_Method__c = 'None',
            Package_Installed_Version_Number__c = '0.1.0-3',
            Installed__c = true,
            Install_Date__c = PREVIOUS_PACKAGE_VERSION_INSTALL_DATETIME,
            Last_Fetched__c = datetime.now(),
            Update_Available__c = false
        );

        insert demoComponent;

        Id demoComponentId = demoComponent.Id;

        QueueGetInstalledPackages queueGetInstalledPackagesJob = new QueueGetInstalledPackages();
    
        Test.startTest();        
        Id jobId = System.enqueueJob(queueGetInstalledPackagesJob);
        QueueGetInstalledPackages.doLater(queueGetInstalledPackagesJob.GetJobInfo());
        Test.stopTest(); 

        Demo_Component__C updatedDemoComponent = [SELECT Id, Update_Available__c, Installed__c, Install_Date__c, Package_Installed_Version_Number__c, Package_Installed_Subscriber_Version_Id__c FROM Demo_Component__c where Id = :demoComponentId LIMIT 1];
        
        System.assertEquals('04t2E000003oc9rQAA', updatedDemoComponent.Package_Installed_Subscriber_Version_Id__c);
        System.assert(true, updatedDemoComponent.Install_Date__c > PREVIOUS_PACKAGE_VERSION_INSTALL_DATETIME);
    }    
   
}