force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Commit_Hash__c.field-meta.xml
<CustomField>
    <fullName>Latest_Commit_Hash__c</fullName>
    <description>Latest Commit Hash of the Master Branch</description>
    <label>Latest Commit Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Installed_Commit_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Source_Installed_Commit_DateTime__c</fullName>
    <label>Source Installed Commit DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueueUpdateComponentSourceCommitInfoTest.cls
@isTest
public with sharing class QueueUpdateComponentSourceCommitInfoTest {
    public static final DateTime CURRENT_COMMIT_DATETIME = (DateTime)Json.deserialize('2020-08-27T19:26:30.000Z', DateTime.class);
    public static final DateTime PREVIOUS_COMMIT_DATETIME = (DateTime)Json.deserialize('2019-08-27T19:26:30.000Z', DateTime.class);


    @testSetup
    static void setup() {
    }

    static testmethod void testJobCurrentCommit() {
        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=false,
            Title__c = 'richTextAreaFSC',
            Installed_Version_Tracking_Method__c = 'Github_Commit',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = ApiCalloutMock.GITHUB_CURRENT_COMMIT_HASH, //Current Commit
            Latest_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Installed__c = true,
            Update_Available__c = false,
            Source_installed_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Source_Installed_Commit_Hash__c = ApiCalloutMock.GITHUB_CURRENT_COMMIT_HASH
        );
        insert demoComponent;

        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock());

        QueueUpdateComponentSourceCommitInfo queueUpdateComponentSourceCommitInfoJob = new QueueUpdateComponentSourceCommitInfo(demoComponent.Id);

        Test.startTest();
        Id jobId = System.enqueueJob(queueUpdateComponentSourceCommitInfoJob);
        QueueUpdateComponentSourceCommitInfo.doLater(queueUpdateComponentSourceCommitInfoJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest();

        Demo_Component__c updatedDemoComponent = [SELECT Id, Github_Repository_URL__c, Latest_Commit_Hash__c, Update_Available__c, Source_installed_Commit_DateTime__c, Source_Installed_Commit_Hash__c FROM Demo_Component__c where Github_Repository_URL__c =:ApiCalloutMock.GITHUB_REPO_URL LIMIT 1];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals(ApiCalloutMock.GITHUB_CURRENT_COMMIT_HASH, updatedDemoComponent.Latest_Commit_Hash__c);
        System.assertEquals(false, updatedDemoComponent.Update_Available__c);
        System.assertEquals(jobId, jobInfo.Id);
    }

    static testmethod void testJobPreviousCommit() {
        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=false,
            Title__c = 'richTextAreaFSC',
            Installed_Version_Tracking_Method__c = 'Github_Commit',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = ApiCalloutMock.GITHUB_PREVIOUS_COMMIT_HASH, //Previous Commit
            Latest_Commit_DateTime__c = PREVIOUS_COMMIT_DATETIME,
            Installed__c = true,
            Update_Available__c = false,
            Source_installed_Commit_DateTime__c = PREVIOUS_COMMIT_DATETIME,
            Source_Installed_Commit_Hash__c = ApiCalloutMock.GITHUB_PREVIOUS_COMMIT_HASH
        );
        insert demoComponent;

        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock());

        QueueUpdateComponentSourceCommitInfo queueUpdateComponentSourceCommitInfoJob = new QueueUpdateComponentSourceCommitInfo(demoComponent.Id);

        Test.startTest();
        Id jobId = System.enqueueJob(queueUpdateComponentSourceCommitInfoJob);
        QueueUpdateComponentSourceCommitInfo.doLater(queueUpdateComponentSourceCommitInfoJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest();

        Demo_Component__c updatedDemoComponent = [SELECT Id, Github_Repository_URL__c, Latest_Commit_Hash__c, Update_Available__c FROM Demo_Component__c where Github_Repository_URL__c =:ApiCalloutMock.GITHUB_REPO_URL LIMIT 1];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals(ApiCalloutMock.GITHUB_CURRENT_COMMIT_HASH, updatedDemoComponent.Latest_Commit_Hash__c);
        System.assertEquals(true, updatedDemoComponent.Update_Available__c);
        System.assertEquals(jobId, jobInfo.Id);
    }



    static testmethod void testJobDifferentTrackingMethod() {
        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=false,
            Title__c = 'richTextAreaFSC',
            Installed_Version_Tracking_Method__c = 'Github_Tag',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = ApiCalloutMock.GITHUB_PREVIOUS_COMMIT_HASH, //Previous Commit
            Latest_Commit_DateTime__c = PREVIOUS_COMMIT_DATETIME,
            Installed__c = true,
            Update_Available__c = false,
            Source_installed_Commit_DateTime__c = PREVIOUS_COMMIT_DATETIME,
            Source_Installed_Commit_Hash__c = ApiCalloutMock.GITHUB_PREVIOUS_COMMIT_HASH
        );
        insert demoComponent;

        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock());

        QueueUpdateComponentSourceCommitInfo queueUpdateComponentSourceCommitInfoJob = new QueueUpdateComponentSourceCommitInfo(demoComponent.Id);

        Test.startTest();
        Id jobId = System.enqueueJob(queueUpdateComponentSourceCommitInfoJob);
        QueueUpdateComponentSourceCommitInfo.doLater(queueUpdateComponentSourceCommitInfoJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest();

        Demo_Component__c updatedDemoComponent = [SELECT Id, Github_Repository_URL__c, Latest_Commit_Hash__c, Update_Available__c FROM Demo_Component__c where Github_Repository_URL__c =:ApiCalloutMock.GITHUB_REPO_URL LIMIT 1];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals(ApiCalloutMock.GITHUB_CURRENT_COMMIT_HASH, updatedDemoComponent.Latest_Commit_Hash__c);
        System.assertEquals(false, updatedDemoComponent.Update_Available__c);
        System.assertEquals(jobId, jobInfo.Id);
    }

    static testmethod void testChildJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock());

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=false,
            Title__c = 'richTextAreaFSC',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = ApiCalloutMock.GITHUB_CURRENT_COMMIT_HASH, //Old Commit
            Latest_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Installed__c = true,
            Update_Available__c = false,
            Source_installed_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Source_Installed_Commit_Hash__c = ApiCalloutMock.GITHUB_PREVIOUS_COMMIT_HASH
        );
        insert demoComponent;
        String ParentJobId = QueuePlatformAsyncEventHelper.generateId();

        QueueUpdateComponentSourceCommitInfo queueUpdateComponentSourceCommitInfoJob = new QueueUpdateComponentSourceCommitInfo(ParentJobId, demoComponent.Id);

        Test.startTest();
            System.enqueueJob(queueUpdateComponentSourceCommitInfoJob);
        Test.stopTest();

        System.assertEquals(ParentJobId, queueUpdateComponentSourceCommitInfoJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID));
    }

    static testmethod void testNoJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock());

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=false,
            Title__c = 'richTextAreaFSC',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = ApiCalloutMock.GITHUB_CURRENT_COMMIT_HASH, //Old Commit
            Latest_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Installed__c = true,
            Update_Available__c = false,
            Source_installed_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Source_Installed_Commit_Hash__c = ApiCalloutMock.GITHUB_PREVIOUS_COMMIT_HASH
        );
        insert demoComponent;
        String ParentJobId = QueuePlatformAsyncEventHelper.generateId();

        QueueUpdateComponentSourceCommitInfo queueUpdateComponentSourceCommitInfoJob = new QueueUpdateComponentSourceCommitInfo(demoComponent.Id);

        Test.startTest();
            System.enqueueJob(queueUpdateComponentSourceCommitInfoJob);
        Test.stopTest();

        System.assertNotEquals(null, queueUpdateComponentSourceCommitInfoJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_ID));
    }


}