force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CMPRefreshCheckerController.cls
public with sharing class CMPRefreshCheckerController {
    @AuraEnabled
    public String recordId { get; set; }

    @AuraEnabled(cacheable=true)
    public static Demo_Component__c runApex(String searchKey){ 

        System.debug('Running CMPRefreshCheckerController.runApex');

        QueueComponentUpdateCheck updateJob = new QueueComponentUpdateCheck(searchKey); 
        ID updateJobbID = System.enqueueJob(updateJob);   

        List<Demo_Component__c> demoComponents = new List<Demo_Component__c>([SELECT Id, Title__c FROM Demo_Component__c WHERE Id = :searchKey LIMIT 1]);
        if(demoComponents.size() > 0){
            system.debug('found Demo Component: ' + demoComponents[0].Title__c);
            //VersionHelper.componentUpdateCheck(demoComponents[0].Id);
            return demoComponents[0];
        }else{
            system.debug('Did not find the component');
        }
        return null;
        
    }
}