force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A short description of the demo</description>
    <inlineHelpText>A short description of the demo</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_SFDX_Package_Alias__c.field-meta.xml
<CustomField>
    <fullName>Latest_SFDX_Package_Alias__c</fullName>
    <description>Package Alias from sfdx-project.json</description>
    <label>Latest SFDX Package Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Subscriber_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Subscriber_Version_Id__c</fullName>
    <label>Package Installed Subscriber Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Version_Number__c</fullName>
    <label>Package Installed Version Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Installed_Commit_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Source_Installed_Commit_DateTime__c</fullName>
    <label>Source Installed Commit DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Installed_Tag_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Source_Installed_Tag_DateTime__c</fullName>
    <label>Source Installed Tag DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/QueueComponentUpdateCheck.cls
public class QueueComponentUpdateCheck implements Queueable {
    String componentId = null;

    public QueueComponentUpdateCheck(String componentId) {
        this.componentId = componentId;
    }

    public void execute(QueueableContext context) {
        System.debug('Start QueueComponentUpdateCheck.execute');
        Boolean updateFlag = false;
        List<Demo_Component__c> demoComponent = [SELECT Id, Description__c, Latest_Commit_DateTime__c, Installation_Type__c, Package_Installed_Version_Number__c, Source_Installed_Commit_Hash__c, Source_Installed_Commit_DateTime__c, SFDX_Installed_Package_Alias__c, Package_Install_Type_Flag__c, Latest_SFDX_Package_Alias__c, Latest_Tag_Commit_Hash__c, Latest_Subscriber_Package_Version_Id__c, Installed_Version_Tracking_Method__c, Package_Installed_Subscriber_Version_Id__c, Installed__c  FROM Demo_Component__c WHERE Id = :componentId LIMIT 1];
        if(demoComponent.size() > 0){
            system.debug('Found Demo Component');
            if(demoComponent[0].Installed__c){
                system.debug('It is installed');
                system.debug('Component Install Type is' + demoComponent[0].Installation_Type__c);
                system.debug('Component Version Tracking Method' + demoComponent[0].Installed_Version_Tracking_Method__c);

                if(demoComponent[0].Installed_Version_Tracking_Method__c == 'SFDX Project'){
                    if(demoComponent[0].Installation_Type__c == 'Package'){
                        if(demoComponent[0].Package_Installed_Subscriber_Version_Id__c != demoComponent[0].Latest_Subscriber_Package_Version_Id__c){
                            system.debug('Component Latest Subscriber Package Version ID of ' + demoComponent[0].Latest_Subscriber_Package_Version_Id__c + ' Is not the same as the installed version of ' + demoComponent[0].Package_Installed_Subscriber_Version_Id__c);
                            updateFlag = true;
                        }
                    }else if(demoComponent[0].Installed_Version_Tracking_Method__c == 'Source' && demoComponent[0].Source_Installed_Tag_Hash__c != ''){
                        if(demoComponent[0].Source_Installed_Tag_DateTime__c < demoComponent[0].Latest_Tag_Commit_DateTime__c){
                            system.debug('Component Source Tag Installed date of ' + demoComponent[0].Source_Installed_Tag_DateTime__c + ' Is less than the latest tag commit date ' + demoComponent[0].Latest_Tag_Commit_DateTime__c);
                            updateFlag = true;
                        }
                    }else if(demoComponent[0].Installed_Version_Tracking_Method__c == 'Source' && demoComponent[0].Source_Installed_Commit_Hash__c != ''){ 
                        if(demoComponent[0].Source_Installed_Commit_DateTime__c < demoComponent[0].Latest_Commit_DateTime__c){
                            system.debug('Component Source Tag Installed date of ' + demoComponent[0].Source_Installed_Tag_DateTime__c + ' Is less than the latest tag commit date ' + demoComponent[0].Latest_Tag_Commit_DateTime__c);
                            updateFlag = true;
                        }                     
                    }
                }
            }           
        }

        if(updateFlag){
            demoComponent[0].Update_Available__c = true;
            update demoComponent;
        }        
    }
}