force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Commit_Hash__c.field-meta.xml
<CustomField>
    <fullName>Latest_Commit_Hash__c</fullName>
    <description>Latest Commit Hash of the Master Branch</description>
    <label>Latest Commit Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Installed_Commit_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Source_Installed_Commit_DateTime__c</fullName>
    <label>Source Installed Commit DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CpmComponentControllerTest.cls
@isTest
public with sharing class CpmComponentControllerTest {
    public static final DateTime CURRENT_COMMIT_DATETIME = (DateTime)Json.deserialize('2020-08-27T19:26:30.000Z', DateTime.class);
    public static final DateTime PREVIOUS_COMMIT_DATETIME = (DateTime)Json.deserialize('2019-08-27T19:26:30.000Z', DateTime.class);

    @testSetup 
    static void setup() {
        List<Demo_Component__c> demoComponents = new List<Demo_Component__c>();

        demoComponents.add(new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.VM_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=false,
            Installed__c = false,
            Title__c = 'Visitor Management Demo Scenario',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = ApiCalloutMock.VM_GITHUB_CURRENT_COMMIT_HASH, //Old Commit
            Latest_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Latest_Package_Version_Deprecated_Flag__c = false
        ));       

        demoComponents.add(new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.RTA_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=false,
            Title__c = 'richTextInputFSC',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = ApiCalloutMock.RTA_GITHUB_CURRENT_COMMIT_HASH, //Old Commit
            Latest_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Installed__c = true,
            Update_Available__c = false,
            Source_installed_Commit_DateTime__c = CURRENT_COMMIT_DATETIME,
            Source_Installed_Commit_Hash__c = ApiCalloutMock.RTA_GITHUB_PREVIOUS_COMMIT_HASH,
            Latest_Package_Version_Deprecated_Flag__c = false    
        ));

        insert demoComponents;
    }
    
    static testmethod void testGetDemoComponents() {
        List<Demo_Component__C> demoComponents = CpmComponentController.getDemoComponents();
        System.assertEquals(2, demoComponents.size());
    }

    static testmethod void testGetInstalledComponents() {
        List<Demo_Component__C> demoComponents = CpmComponentController.getInstalledComponents(null);
        System.assertEquals(1, demoComponents.size());
        System.assertEquals('richTextInputFSC', demoComponents[0].Title__c);
    }

    static testmethod void testGetAvailableComponents() {
        List<Demo_Component__C> demoComponents = CpmComponentController.getAvailableComponents(null);
        System.assertEquals(1, demoComponents.size());
        System.assertEquals('Visitor Management Demo Scenario', demoComponents[0].Title__c);
    }    

    static testmethod void testGetInstalledComponentsSearch() {
        Demo_Component__c demoComponent = [SELECT Id FROM Demo_Component__c WHERE Title__c = 'richTextInputFSC'];

        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = demoComponent.Id;
        Test.setFixedSearchResults(new List<Id>(fixedSearchResults));

        List<Demo_Component__C> demoComponents = CpmComponentController.getInstalledComponents('richTextInputFSC');
        System.assertEquals(1, demoComponents.size());
        System.assertEquals('richTextInputFSC', demoComponents[0].Title__c);
    }

    static testmethod void testGetAvailableComponentsSearch() {
        Demo_Component__c demoComponent = [SELECT Id FROM Demo_Component__c WHERE Title__c = 'Visitor Management Demo Scenario'];

        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = demoComponent.Id;
        Test.setFixedSearchResults(new List<Id>(fixedSearchResults));

        List<Demo_Component__C> demoComponents = CpmComponentController.getAvailableComponents('Visitor');
        System.assertEquals(1, demoComponents.size());
        System.assertEquals('Visitor Management Demo Scenario', demoComponents[0].Title__c);
    }    

}