force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_SFDX_Package_Alias__c.field-meta.xml
<CustomField>
    <fullName>Latest_SFDX_Package_Alias__c</fullName>
    <description>Package Alias from sfdx-project.json</description>
    <label>Latest SFDX Package Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_SFDX_Package_Version_Name__c.field-meta.xml
<CustomField>
    <fullName>Latest_SFDX_Package_Version_Name__c</fullName>
    <description>Version Name from SFDX-Package.json file</description>
    <label>Latest SFDX Package Version Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QueueUpdateComponentFromSFDX.cls
public class QueueUpdateComponentFromSFDX implements Queueable, Database.AllowsCallouts  {
    /*************STANDARD HELPER VARIABLES / FUNCTIONS*************/
    public final String JOBNAME = 'QueueUpdateComponentFromSFDX';
    Map<String,String> jobInfo = new Map<String,String>{'jobName' => JOBNAME, 'ApexClassName' => QueueUpdateComponentFromSFDX.class.getName()};

    public String getJobName() {
    return this.JOBNAME;
    }

    public String getJobInfo(String key) {
    return this.jobInfo.get(key);
    }

    public Map<String,String> getJobInfo() {
    return this.jobInfo;
    }    

    /*************QUEUEABLE SPECIFIC VARIABLES / FUNCTIONS*************/
    Id demoComponentId = null;
    String githubUrl = null;

    /*************CONSTRUCTORS*************/    
    public QueueUpdateComponentFromSFDX(ID parentJobId, Id demoComponentId, String githubUrl) {
        this.demoComponentId = demoComponentId;
        this.githubUrl = githubUrl;       
        this.jobInfo.put('parentJobId', parentJobId);
    }

    public QueueUpdateComponentFromSFDX(Id demoComponentId, String githubUrl) {
        this.demoComponentId = demoComponentId;
        this.githubUrl = githubUrl;
    }


    /*************EXECUTE METHOD*************/   
    public void execute(QueueableContext context) {
        /*************STANDARD EXECUTE STARTER*************/
        this.jobInfo.put('jobId', context.getJobId());
        QueuePlatformEventHelper.publishAsyncPlatformEvent(this.jobInfo,'Processing');

        System.debug('Processing ' + this.githubUrl);   
        doLater(this.jobInfo, this.demoComponentId, this.githubUrl);

    }

    @future(callout=true)
    public static void doLater(Map<String, String> jobInfo, Id demoComponentId, String githubUrl) {
        Boolean triggerPackageUpdate = false;
        GithubSFDXProjectDotJSON githubSFDXProjectDotJSON = new GithubSFDXProjectDotJSON();

        try {
            githubSFDXProjectDotJSON = GithubAPIHelper.getGithubSFDXProjectDotJSON(githubUrl);

            List<Demo_Component__c> demoComponent = [SELECT Id, Github_Repository_URL__c, Latest_Subscriber_Package_Version_Id__c, Installed_Version_Tracking_Method__c, SFDX_Package_Enabled_Flag__c FROM Demo_Component__c WHERE Id = :demoComponentId LIMIT 1];
            if(githubSFDXProjectDotJSON != null){
                if(githubSFDXProjectDotJSON.packageDirectories != null && githubSFDXProjectDotJSON.packageDirectories.size() > 0){
                    for(GithubPackageDirectory thisPackageDirectory: (List<GithubPackageDirectory>) githubSFDXProjectDotJSON.packageDirectories){
                        if(thisPackageDirectory.defaultDirectory == true){
                            System.debug('Found the default package directory, this is an SFDX Enabled Project!');

                            demoComponent[0].Package_Install_Type_Flag__c = true;
                            demoComponent[0].SFDX_Package_Enabled_Flag__c = true;
                            demoComponent[0].SFDX_Package_Name__c = thisPackageDirectory.packageName;
                            demoComponent[0].Latest_SFDX_Package_Version_Name__c = thisPackageDirectory.versionName;
                            demoComponent[0].Latest_SFDX_Package_Version_Description__c = thisPackageDirectory.versionDescription;

                            //Processing Dependencies
                            if(thisPackageDirectory.dependencies != null && thisPackageDirectory.dependencies.size() > 0){
                                List<String> dependentPackageSubscriberPackageVersionIds = new List<String>();
                                for(Map<String,String> thisDependency: (List<map<string,string>>) thisPackageDirectory.dependencies){
                                    if(thisDependency.containsKey('packageName')){
                                        dependentPackageSubscriberPackageVersionIds.add((String)thisDependency.get('packageName'));
                                    }
                                }
                                System.debug('Found some dependent Packages in SFDX-Project.json, will address later: ' + dependentPackageSubscriberPackageVersionIds);
                            }
                        }else{
                            System.debug('This is not the default package directory, skipping');
                        }
                    }

                    if(demoComponent[0].Latest_Subscriber_Package_Version_Id__c != githubSFDXProjectDotJSON.getLatestVersionPackageVersionId()){
                        System.debug('Package Versions are different, QueueUpdateComponentFromPackageVersion');
                        demoComponent[0].Latest_SFDX_Package_Alias__c = githubSFDXProjectDotJSON.getLatestVersionAlias();
                        demoComponent[0].Latest_Subscriber_Package_Version_Id__c = githubSFDXProjectDotJSON.getLatestVersionPackageVersionId();
                        triggerPackageUpdate = true;

                        if(demoComponent[0].Installed__c){
                            System.debug('Checking to see if update is available');
                            if(demoComponent[0].Installed_Version_Tracking_Method__c == 'SFDX Project' ){
                                System.debug('Update Available');
                                demoComponent[0].Update_Available__c = true;
                            }
                        }

                    }
                }

                update demoComponent;

                QueuePlatformEventHelper.publishPlatformEvent(jobInfo,'Completed', new Map<String,String>{
                    'Toast_Title__c' => 'Job Completion Notification',
                    'Toast_Message__c' => jobInfo.get('jobId') + ' - ' + jobInfo.get('jobName') + ' Completed Successfully',
                    'Toast_Variant__c' => 'success'}) ;                  

                if(triggerPackageUpdate){
                    QueueUpdateComponentFromPackageVersion queueUpdateComponentFromPackageVersionJob = new QueueUpdateComponentFromPackageVersion(new List<String>{githubSFDXProjectDotJSON.getLatestVersionPackageVersionId()}, new Map<String,String>()); 
                    ID JobID = System.enqueueJob(queueUpdateComponentFromPackageVersionJob);    
                }

            }else{
                System.debug('sfdx-project.json not found');  
            }
        }catch (Exception e) {
            QueuePlatformEventHelper.publishPlatformEvent(jobInfo,'Failed', new Map<String,String>{
                'Toast_Title__c' => 'Job Completion Notification',
                'Toast_Message__c' => 'QueueUpdateComponentFromSFDX Failed. Error: ' + e.getMessage(),
                'Toast_Variant__c' => 'error'}) ;    
        }  

    
    }

}    