force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A short description of the demo</description>
    <inlineHelpText>A short description of the demo</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Name__c</fullName>
    <description>Name of the Package. Can be sourced by sfdx-project.json or tooling api.</description>
    <label>Package Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/POC_Email__c.field-meta.xml
<CustomField>
    <fullName>POC_Email__c</fullName>
    <description>Email for the point of contact for the demo</description>
    <inlineHelpText>Email for the point of contact for the demo</inlineHelpText>
    <label>POC Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CpmComponentController.cls
public with sharing class CpmComponentController {

    @AuraEnabled(cacheable=true)
    public static list<Demo_Component__c> getDemoComponents(String recordId){
        return [SELECT Id, Title__c, Name, Description__c, Package_Name__c, Update_Available__c, Installed__c, POC_Email__c, POC_Name__c, Github_Repository_URL__c, SFDX_Package_Enabled_Flag__c FROM Demo_Component__c];
    }    

    @AuraEnabled(cacheable=true)
    public static list<Demo_Component__c> getInstalledComponents(String recordId){
        return [SELECT Id, Title__c, Name, Description__c, Package_Name__c, Update_Available__c, Installed__c, POC_Email__c, POC_Name__c, Github_Repository_URL__c, SFDX_Package_Enabled_Flag__c FROM Demo_Component__c WHERE Installed__c = true];
    }

    @AuraEnabled(cacheable=true)
    public static list<Demo_Component__c> getAvailableComponents(String recordId){
        return [SELECT Id, Title__c, Name, Description__c, Package_Name__c, Update_Available__c, Installed__c, POC_Email__c, POC_Name__c, Github_Repository_URL__c, SFDX_Package_Enabled_Flag__c FROM Demo_Component__c WHERE Installed__c = false];
    }    
}