force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Demo_Component_Manager_Settings__c/Demo_Component_Manager_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Demo Component Manager Settings</label>
</CustomObject>

force-app/main/default/classes/CpmComponentInstallCheckerControllerTest.cls
@isTest
public with sharing class CpmComponentInstallCheckerControllerTest {
    @testSetup 
    static void setup() {
    }
    
    static testmethod void testrunApex() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock());

        Demo_Component_Manager_Settings__c newAppSetting = new Demo_Component_Manager_Settings__c();
        insert newAppSetting;

        Test.startTest();        
            CpmComponentInstallCheckerController.runApex(true);
        Test.stopTest(); 

       Demo_Component__C demoComponentVM = [SELECT Id, Title__c, Installed__c, Installed_Version_Tracking_Method__c, Update_Available__c, Latest_Package_Version_Deprecated_Flag__c, Source_Installed_Commit_Hash__c FROM Demo_Component__c where Github_Repository_URL__c =:ApiCalloutMock.VM_GITHUB_REPO_URL LIMIT 1];
                
        System.assertEquals('gpbu visitor management', demoComponentVM.Title__c); 
        System.assertEquals('Github_Commit', demoComponentVM.Installed_Version_Tracking_Method__c); 
    }


    static testmethod void testrunApexNoSetting() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock());
        
        Test.startTest();        
            CpmComponentInstallCheckerController.runApex(false);
        Test.stopTest(); 

        List<Demo_Component_Manager_Settings__c> appSettings = [SELECT Id, Last_Library_Refresh_Date__c, Initial_Config_Flag__c FROM Demo_Component_Manager_Settings__c];
       
       System.assertEquals(1, appSettings.size());  
    }    

    static testmethod void testgetAppSettings() {

        Demo_Component_Manager_Settings__c newAppSetting = new Demo_Component_Manager_Settings__c();
        newAppSetting.Initial_Config_Flag__c = true;
        insert newAppSetting;


        Test.startTest();        
            Demo_Component_Manager_Settings__c demoComponentManagerSetting = CpmComponentInstallCheckerController.getAppSettings();
        Test.stopTest(); 
           
        System.assertEquals(true, demoComponentManagerSetting.Initial_Config_Flag__c);  
    }

    static testmethod void testgetAppSettingsNoSetting() {

        Test.startTest();        
            Demo_Component_Manager_Settings__c demoComponentManagerSetting = CpmComponentInstallCheckerController.getAppSettings();
        Test.stopTest(); 
           
        System.assertEquals(false, demoComponentManagerSetting.Initial_Config_Flag__c);  
    }
}