force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_SFDX_Package_Alias__c.field-meta.xml
<CustomField>
    <fullName>Latest_SFDX_Package_Alias__c</fullName>
    <description>Package Alias from sfdx-project.json</description>
    <label>Latest SFDX Package Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_SFDX_Package_Version_Name__c.field-meta.xml
<CustomField>
    <fullName>Latest_SFDX_Package_Version_Name__c</fullName>
    <description>Version Name from SFDX-Package.json file</description>
    <label>Latest SFDX Package Version Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Subscriber_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Subscriber_Version_Id__c</fullName>
    <label>Package Installed Subscriber Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Version_Number__c</fullName>
    <label>Package Installed Version Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Installed_Package_Version_Name__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Installed_Package_Version_Name__c</fullName>
    <label>SFDX Installed Package Version Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueueUpdateComponentFromSFDXTest.cls
@isTest
public with sharing class QueueUpdateComponentFromSFDXTest {

    @testSetup 
    static void setup() {
    }
    
    static testmethod void testJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.VM_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario'
        );

        insert demoComponent;

        QueueUpdateComponentFromSFDX queueUpdateComponentFromSFDXJob = new QueueUpdateComponentFromSFDX(demoComponent.Id);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueUpdateComponentFromSFDXJob);
        QueueUpdateComponentFromSFDX.doLater(queueUpdateComponentFromSFDXJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest(); 
        
        
        Demo_Component__C updatedDemoComponent = [SELECT Id, SFDX_Package_Name__c, Latest_SFDX_Package_Alias__c FROM Demo_Component__c where Id =:demoComponent.Id LIMIT 1];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals('Visitor Management Demo Scenario', updatedDemoComponent.SFDX_Package_Name__c);
        System.assertEquals('Visitor Management Demo Scenario@0.1.1-1', updatedDemoComponent.Latest_SFDX_Package_Alias__c);       
        System.assertEquals(jobId, jobInfo.Id);
    }

    static testmethod void testChildJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.VM_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario',
            Last_Fetched__c = datetime.now(),
            Latest_SFDX_Package_Alias__c = 'Visitor Management Demo Scenario@0.1.1-1',
            Latest_SFDX_Package_Version_Name__c = 'ver 1.0',
            SFDX_Package_Name__c = 'Visitor Management Demo Scenario'
        );

        insert demoComponent;
        
        String ParentJobId = QueuePlatformAsyncEventHelper.generateId();

        QueueUpdateComponentFromSFDX queueUpdateComponentFromSFDXJob = new QueueUpdateComponentFromSFDX(ParentJobId, demoComponent.Id);
        
        Test.startTest();        
            System.enqueueJob(queueUpdateComponentFromSFDXJob);
        Test.stopTest(); 
        
        System.assertEquals(ParentJobId, queueUpdateComponentFromSFDXJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID));
    }

    static testmethod void testNoSFDXProjectDotJSON() {
        Test.setMock(HttpCalloutMock.class, new ApiError404CalloutMock());

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.VM_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario'
        );

        insert demoComponent;

        QueueUpdateComponentFromSFDX queueUpdateComponentFromSFDXJob = new QueueUpdateComponentFromSFDX(demoComponent.Id);
        
        Test.startTest();        
        System.enqueueJob(queueUpdateComponentFromSFDXJob);
        QueueUpdateComponentFromSFDX.doLater(queueUpdateComponentFromSFDXJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest(); 
        
        
        Demo_Component__C updatedDemoComponent = [SELECT Id, SFDX_Package_Enabled_Flag__c FROM Demo_Component__c where Id =:demoComponent.Id LIMIT 1];
        System.assertEquals(false, updatedDemoComponent.SFDX_Package_Enabled_Flag__c);
    }

    static testmethod void testNotAnSFDXProject() {
        Test.setMock(HttpCalloutMock.class, new ApiError404CalloutMock());

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = null,
            SFDX_Package_Enabled_Flag__c=false,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'TestTest'
        );

        insert demoComponent;

        QueueUpdateComponentFromSFDX queueUpdateComponentFromSFDXJob = new QueueUpdateComponentFromSFDX(demoComponent.Id);
        
        Test.startTest();        
        System.enqueueJob(queueUpdateComponentFromSFDXJob);
        QueueUpdateComponentFromSFDX.doLater(queueUpdateComponentFromSFDXJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest(); 
        
        
        Demo_Component__C updatedDemoComponent = [SELECT Id, Title__c FROM Demo_Component__c where Id =:demoComponent.Id LIMIT 1];
        System.assertEquals('TestTest', updatedDemoComponent.Title__c);
    }

    static testmethod void testNoDemoComponentFound() {
        Test.setMock(HttpCalloutMock.class, new ApiError404CalloutMock());

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.VM_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=false,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'TestTest'
        );

        insert demoComponent;
        Id demoComponentId = demoComponent.Id;
        delete demoComponent;

        QueueUpdateComponentFromSFDX queueUpdateComponentFromSFDXJob = new QueueUpdateComponentFromSFDX(demoComponentId);
        
        Test.startTest();        
        System.enqueueJob(queueUpdateComponentFromSFDXJob);
        QueueUpdateComponentFromSFDX.doLater(queueUpdateComponentFromSFDXJob.GetJobInfo(), demoComponentId);
        Test.stopTest(); 
        
        System.assertEquals(QueuePlatformAsyncEventHelper.STAGE_FAILED, queueUpdateComponentFromSFDXJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_CURRENT_JOB_STAGE));
    }

    static testmethod void testUpdate() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.VM_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario',
            Last_Fetched__c = datetime.now(),
            Latest_SFDX_Package_Alias__c = 'Visitor Management Demo Scenario@0.1.0-3',
            Latest_SFDX_Package_Version_Name__c = 'ver 1.0',
            Latest_Package_Version__c = '0.1.0-3',
            Subscriber_Package_Id__c = '0333h000000AY9lAAG',
            Installed__c = true,
            Installed_Version_Tracking_Method__c = 'SFDX_Project',
            SFDX_Installed_Package_Alias__c = 'Visitor Management Demo Scenario@0.1.0-3',
            SFDX_Installed_Package_Version_Name__c = 'ver 1.0',
            SFDX_Package_Name__c = 'Visitor Management Demo Scenario',
            Package_Installed_Version_Number__c = '0.1.0-3', 
            Package_Installed_Subscriber_Version_Id__c = '04t3h000004bdNOAAY'
        );

        insert demoComponent;

        QueueUpdateComponentFromSFDX queueUpdateComponentFromSFDXJob = new QueueUpdateComponentFromSFDX(demoComponent.Id);
        
        Test.startTest();        
            System.enqueueJob(queueUpdateComponentFromSFDXJob);
            QueueUpdateComponentFromSFDX.doLater(queueUpdateComponentFromSFDXJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest(); 
        
        Demo_Component__C updatedDemoComponent = [SELECT Id, Update_Available__c, Latest_SFDX_Package_Alias__c, Latest_Subscriber_Package_Version_Id__c FROM Demo_Component__c where Id =:demoComponent.Id LIMIT 1];
        System.assertEquals(true, updatedDemoComponent.Update_Available__c);
        System.assertEquals('Visitor Management Demo Scenario@0.1.1-1', updatedDemoComponent.Latest_SFDX_Package_Alias__c);
        System.assertEquals('04t3h000004bdPAAAY', updatedDemoComponent.Latest_Subscriber_Package_Version_Id__c);        
    }



}