force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Name__c</fullName>
    <description>Name of the Package. Can be sourced by sfdx-project.json or tooling api.</description>
    <label>Package Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QueueUpdateComponentFromPackageVersion.cls
public class QueueUpdateComponentFromPackageVersion implements Queueable, Database.AllowsCallouts {
    /*************STANDARD HELPER VARIABLES / FUNCTIONS*************/
    Map<String,String> jobInfo = new Map<String,String>{
      QueuePlatformAsyncEventHelper.FIELD_JOB_NAME =>  'Update Component Package Info', 
      QueuePlatformAsyncEventHelper.FIELD_APEX_CLASS_NAME => QueueUpdateComponentFromPackageVersion.class.getName()
  };

  public Map<String,String> GetJobInfo() {
      return this.jobInfo;
  }    

  public String GetJobInfo(String key) {
      return this.jobInfo.get(key);
  }

  public void SetJobInfo(String key, String value) {
      this.jobInfo.put(key, value);
  }

  public void SetJobStage(String value) {
      this.jobInfo.put(QueuePlatformAsyncEventHelper.FIELD_CURRENT_JOB_STAGE, value);  
  }   

  /*************QUEUEABLE SPECIFIC VARIABLES / FUNCTIONS*************/
  Id demoComponentId = null;
  String subscriberPackageVersionId;

  /*************CONSTRUCTORS*************/      
  public QueueUpdateComponentFromPackageVersion(String parentJobId, Id demoComponentId, String subscriberPackageVersionId) {
    this.SetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_ID, QueuePlatformAsyncEventHelper.generateId()); 
    this.SetJobStage(QueuePlatformAsyncEventHelper.STAGE_QUEUED); 
    this.SetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID, parentJobId);    
    QueuePlatformAsyncEventHelper.publishPlatformEvent(this.GetJobInfo());
    this.demoComponentId = demoComponentId;
    this.subscriberPackageVersionId = subscriberPackageVersionId;
  }

  public QueueUpdateComponentFromPackageVersion(Id demoComponentId, String subscriberPackageVersionId) {
    this.SetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_ID, QueuePlatformAsyncEventHelper.generateId()); 
    this.SetJobStage(QueuePlatformAsyncEventHelper.STAGE_QUEUED); 
    QueuePlatformAsyncEventHelper.publishPlatformEvent(this.GetJobInfo());
    this.demoComponentId = demoComponentId;
    this.subscriberPackageVersionId = subscriberPackageVersionId;
  }

  /*************EXECUTE METHOD*************/   
  public void execute(QueueableContext context) {
      /*************STANDARD EXECUTE STARTER*************/
      System.debug('Running ' + QueueUpdateComponentFromPackageVersion.class.getName() );
      this.SetJobStage(QueuePlatformAsyncEventHelper.STAGE_PROCESSING);
      QueuePlatformAsyncEventHelper.publishPlatformEvent(this.GetJobInfo());

    doLater(this.jobInfo, this.demoComponentId, subscriberPackageVersionId);
  }

  @future(callout=true)
  private static void doLater(Map<String, String> jobInfo,Id demoComponentId,String subscriberPackageVersionId) {
    List<Demo_Component__c> demoComponentLookup = [SELECT Id, Github_Repository_URL__c, Installed__c, Latest_Subscriber_Package_Version_Id__c, Installed_Version_Tracking_Method__c, SFDX_Package_Enabled_Flag__c FROM Demo_Component__c WHERE Id = :demoComponentId LIMIT 1];  
    if (demoComponentLookup.size() > 0) {
      System.debug('Successfully found Demo Component');
      Boolean toolingAPISuccessFlag = false;

      MetadataInstalledPackageResponseRecord metadataInstalledPackageResponseRecord = new MetadataInstalledPackageResponseRecord();
      MetadataSubscriberPackageVersion metadataSubscriberPackageVersion = new MetadataSubscriberPackageVersion();
      MetadataSubscriberPackage metadataSubscriberPackage = new MetadataSubscriberPackage();


      metadataSubscriberPackageVersion = MetadataAPIHelper.getSubscriberPackageVersion(subscriberPackageVersionId);
      if (metadataSubscriberPackageVersion != null) {
        System.debug('Successfully found Subscriber Package Version Info from Tooling API');
        metadataSubscriberPackage = MetadataAPIHelper.getSubscriberPackage(metadataSubscriberPackageVersion.subscriberPackageId);
        if (metadataSubscriberPackage != null) {
          System.debug('Successfully found Subscriber Package Info from Tooling API');
          metadataInstalledPackageResponseRecord.subscriberPackageId = subscriberPackageVersionId;
          metadataInstalledPackageResponseRecord.subscriberpackage = metadataSubscriberPackage;
          metadataInstalledPackageResponseRecord.subscriberPackageVersion = metadataSubscriberPackageVersion;
          toolingAPISuccessFlag = true;
        }else{
          System.debug('Could not find Subscriber Package Version Info from Tooling API');
        }
      }else{
        System.debug('Could not find Subscriber Package Version Info from Tooling API');
      }

      if(toolingAPISuccessFlag){
        Demo_Component__c demoComponent = demoComponentLookup[0];
        demoComponent.Subscriber_Package_Id__c = metadataInstalledPackageResponseRecord.subscriberPackage.id;
        demoComponent.Package_Name__c = metadataInstalledPackageResponseRecord.subscriberPackage.name;
        demoComponent.Latest_Subscriber_Package_Version_Id__c = metadataInstalledPackageResponseRecord.subscriberPackageVersion.id;
        demoComponent.Latest_Package_Version__c = metadataInstalledPackageResponseRecord.subscriberPackageVersion.getSubscriberPackageVersionNumberText();
        demoComponent.Latest_Package_Version_Name__c = metadataInstalledPackageResponseRecord.subscriberPackageVersion.name;
        update demoComponent;


        if(null != metadataInstalledPackageResponseRecord.subscriberPackageVersion.dependencies){
          if(metadataInstalledPackageResponseRecord.subscriberPackageVersion.dependencies.ids.size() > 0){
            List<String> dependentPackageSubscriberPackageVersionIds = new List<String>();
            for(Map<String,String> dependency: metadataInstalledPackageResponseRecord.subscriberPackageVersion.dependencies.ids){
              dependentPackageSubscriberPackageVersionIds.add(dependency.get('subscriberPackageVersionId'));
            }
            QueueProcessDependentPackages queueProcessDependentPackagesJob = new QueueProcessDependentPackages(jobInfo.get(QueuePlatformAsyncEventHelper.FIELD_JOB_ID),demoComponent.Id, dependentPackageSubscriberPackageVersionIds); 
            System.enqueueJob(queueProcessDependentPackagesJob);
          }
        }

      }
    }

        jobInfo.put(QueuePlatformAsyncEventHelper.FIELD_CURRENT_JOB_STAGE, QueuePlatformAsyncEventHelper.STAGE_COMPLETED);
        QueuePlatformAsyncEventHelper.publishPlatformEvent(jobInfo);   
  }
}