force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A short description of the demo</description>
    <inlineHelpText>A short description of the demo</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Commit_Hash__c.field-meta.xml
<CustomField>
    <fullName>Latest_Commit_Hash__c</fullName>
    <description>Latest Commit Hash of the Master Branch</description>
    <label>Latest Commit Hash</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueueUpdateComponentFromGithubRepoTest.cls
@isTest
public with sharing class QueueUpdateComponentFromGithubRepoTest {
    public static final String OLD_COMMIT = 'ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81';
    public static final String CURRENT_COMMIT = 'ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81';

    @testSetup 
    static void setup() {
        List<Demo_Component__c> demoComponents = new List<Demo_Component__c>();
        demoComponents.add(new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.RTA_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'richTextAreaFSC',
            Last_Fetched__c = datetime.now(),
            Latest_Commit_Hash__c = 'ba99ca2ffdd0e25596be4e1fa9cbc18bb2f57f81',
            Latest_Commit_DateTime__c = (DateTime)Json.deserialize('2020-08-27T19:26:30.000Z', DateTime.class)
        ));

        insert demoComponents;
    }
    
    static testmethod void testJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 
        Demo_Component__C demoComponent = new Demo_Component__C();
        
        demoComponent = [SELECT Id, Github_Repository_URL__c FROM Demo_Component__c where Github_Repository_URL__c =:ApiCalloutMock.RTA_GITHUB_REPO_URL LIMIT 1];
        QueueUpdateComponentFromGithubRepo queueUpdateComponentFromGithubRepoJob = new QueueUpdateComponentFromGithubRepo(demoComponent.Id);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueUpdateComponentFromGithubRepoJob);
        QueueUpdateComponentFromGithubRepo.doLater(queueUpdateComponentFromGithubRepoJob.GetJobInfo(), demoComponent.Id);
        Test.stopTest(); 
        
        
        Demo_Component__C updatedDemoComponent = [SELECT Id, POC_Name__c, Description__c FROM Demo_Component__c where Id =:demoComponent.Id LIMIT 1];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals('David Larrimore', updatedDemoComponent.POC_Name__c);
        System.assertEquals(jobId, jobInfo.Id);
        System.assertNotEquals(null, updatedDemoComponent.Description__c);
        System.assertNotEquals(null, queueUpdateComponentFromGithubRepoJob.GetJobInfo());
    }

    static testmethod void testChildJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 
        Demo_Component__C demoComponent = new Demo_Component__C();
        
        demoComponent = [SELECT Id, Github_Repository_URL__c FROM Demo_Component__c where Github_Repository_URL__c =:ApiCalloutMock.RTA_GITHUB_REPO_URL LIMIT 1];
        String ParentJobId = QueuePlatformAsyncEventHelper.generateId();

        QueueUpdateComponentFromGithubRepo queueUpdateComponentFromGithubRepoJob = new QueueUpdateComponentFromGithubRepo(ParentJobId, demoComponent.Id);
        
        Test.startTest();        
            System.enqueueJob(queueUpdateComponentFromGithubRepoJob);
        Test.stopTest(); 
        
        System.assertEquals(ParentJobId, queueUpdateComponentFromGithubRepoJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID));
    }

}