force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Subscriber_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Subscriber_Version_Id__c</fullName>
    <label>Package Installed Subscriber Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Version_Number__c</fullName>
    <label>Package Installed Version Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Name__c</fullName>
    <description>Name of the Package. Can be sourced by sfdx-project.json or tooling api.</description>
    <label>Package Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueueUpdateComponentFromPKGVersionTest.cls
@isTest
public with sharing class QueueUpdateComponentFromPKGVersionTest {
    public static final DateTime CURRENT_PACKAGE_VERSION_INSTALL_DATETIME = (DateTime)Json.deserialize('2020-08-27T19:26:30.000Z', DateTime.class);
    public static final DateTime PREVIOUS_PACKAGE_VERSION_INSTALL_DATETIME = (DateTime)Json.deserialize('2019-08-27T19:26:30.000Z', DateTime.class);

    @testSetup 
    static void setup() {

    }
    
    static testmethod void testJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.RTA_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario',
            Package_Name__c = 'Visitor Management Demo Scenario',
            Latest_Package_Version_Name__c = '',
            Latest_Package_Version__c = '0.1.1-1',
            Subscriber_Package_Id__c = ApiCalloutMock.SUBSCRIBER_PACKAGE_ID,
            Latest_Subscriber_Package_Version_Id__c = '',
            Last_Fetched__c = datetime.now(),
            Update_Available__c = false
        );
        insert demoComponent;


        QueueUpdateComponentFromPackageVersion queueUpdateComponentFromPackageVersionJob = new QueueUpdateComponentFromPackageVersion(demoComponent.Id, ApiCalloutMock.CURRENT_SUBSCRIBER_PACKAGE_VERSION_ID);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueUpdateComponentFromPackageVersionJob);
        QueueUpdateComponentFromPackageVersion.doLater(queueUpdateComponentFromPackageVersionJob.GetJobInfo(), demoComponent.Id, ApiCalloutMock.CURRENT_SUBSCRIBER_PACKAGE_VERSION_ID);
        Test.stopTest(); 
        
        
        Demo_Component__C updatedDemoComponent = [SELECT Id, Latest_Package_Version_Name__c FROM Demo_Component__c where Subscriber_Package_Id__c=:ApiCalloutMock.SUBSCRIBER_PACKAGE_ID LIMIT 1];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals('ver 1.0', updatedDemoComponent.Latest_Package_Version_Name__c);
        System.assertEquals(jobId, jobInfo.Id);
    }


    static testmethod void testChildJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.RTA_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario',
            Package_Name__c = 'Visitor Management Demo Scenario',
            Latest_Package_Version_Name__c = '',
            Latest_Package_Version__c = '0.1.1-1',
            Subscriber_Package_Id__c = ApiCalloutMock.SUBSCRIBER_PACKAGE_ID,
            Latest_Subscriber_Package_Version_Id__c = '',
            Last_Fetched__c = datetime.now(),
            Update_Available__c = false
        );
        insert demoComponent;

        String ParentJobId = QueuePlatformAsyncEventHelper.generateId();
        QueueUpdateComponentFromPackageVersion queueUpdateComponentFromPackageVersionJob = new QueueUpdateComponentFromPackageVersion(ParentJobId, demoComponent.Id, ApiCalloutMock.CURRENT_SUBSCRIBER_PACKAGE_VERSION_ID);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueUpdateComponentFromPackageVersionJob);
        Test.stopTest(); 
        
        System.assertEquals(ParentJobId, queueUpdateComponentFromPackageVersionJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID));
    }

    static testmethod void testJobUpdate() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 

        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.RTA_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario',
            Package_Name__c = 'Visitor Management Demo Scenario',
            Subscriber_Package_Id__c = ApiCalloutMock.SUBSCRIBER_PACKAGE_ID,
            Latest_Package_Version_Name__c = 'ver 0.1',
            Latest_Package_Version__c = '0.1.0-3',
            Latest_Subscriber_Package_Version_Id__c = ApiCalloutMock.PREVIOUS_SUBSCRIBER_PACKAGE_VERSION_ID,
            Package_Installed_Subscriber_Version_Id__c = ApiCalloutMock.PREVIOUS_SUBSCRIBER_PACKAGE_VERSION_ID,
            Installed_Version_Tracking_Method__c = 'None',
            Package_Installed_Version_Number__c = '0.1.0-3',
            Installed__c = true,
            Last_Fetched__c = datetime.now(),
            Update_Available__c = false
        );
        insert demoComponent;


        QueueUpdateComponentFromPackageVersion queueUpdateComponentFromPackageVersionJob = new QueueUpdateComponentFromPackageVersion(demoComponent.Id, ApiCalloutMock.CURRENT_SUBSCRIBER_PACKAGE_VERSION_ID);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueUpdateComponentFromPackageVersionJob);
        QueueUpdateComponentFromPackageVersion.doLater(queueUpdateComponentFromPackageVersionJob.GetJobInfo(), demoComponent.Id, ApiCalloutMock.CURRENT_SUBSCRIBER_PACKAGE_VERSION_ID);
        Test.stopTest(); 
        
        Demo_Component__C updatedDemoComponent = [SELECT Id, Update_Available__c FROM Demo_Component__c where Subscriber_Package_Id__c=:ApiCalloutMock.SUBSCRIBER_PACKAGE_ID LIMIT 1];
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals(true, updatedDemoComponent.Update_Available__c);
    }


    //Test Case for Dependent Components

}