force-app/main/default/objects/CPM_Async_Event__e/CPM_Async_Event__e.object-meta.xml
<CustomObject>
    <label>CPM Async Event</label>
    <pluralLabel>CPM Async Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPM_Async_Event__e/fields/ApexClass_Name__c.field-meta.xml
<CustomField>
    <fullName>ApexClass_Name__c</fullName>
    <label>ApexClass Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Id__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Id__c</fullName>
    <label>AsyncApexJob Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Name__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Name__c</fullName>
    <label>AsyncApexJob Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Status__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Status__c</fullName>
    <description>Queued, Processing, Completed, Completed with Warnings, Completed with Errors, Failed</description>
    <label>AsyncApexJob Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/Send_Toast__c.field-meta.xml
<CustomField>
    <fullName>Send_Toast__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send toast to UI</description>
    <label>Send_Toast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CpmRefreshCheckerController.cls
public with sharing class CpmRefreshCheckerController {

    @AuraEnabled
    public static List<ID> runApex(String demoComponentId){ 
        System.debug('Running CMPRefreshCheckerController.runApex');
        List<ID> jobIds = new List<ID>();
        ID jobId;

        List<Demo_Component__c> demoComponent = [SELECT Id, Github_Repository_URL__c, Source_Install_Type_Flag__c, SFDX_Package_Enabled_Flag__c FROM Demo_Component__c WHERE Id = :demoComponentId LIMIT 1];
        if(demoComponent.size() > 0){

            if(demoComponent[0].SFDX_Package_Enabled_Flag__c){
                QueueUpdateComponentFromSFDX queueUpdateComponentFromSFDXJob = new QueueUpdateComponentFromSFDX(demoComponentId, demoComponent[0].Github_Repository_URL__c); 
                List<AsyncApexJob> existingJobs = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE Status IN ('Holding','Queued','Preparing','Processing') AND ApexClass.Name = :queueUpdateComponentFromSFDXJob.getJobInfo('ApexClassName') LIMIT 1];
                if (existingJobs.size() == 0){
                    jobId = System.enqueueJob(queueUpdateComponentFromSFDXJob);
                    jobIds.add(jobId);    
                           
                    EventBus.publish(new CPM_Async_Event__e(
                        ApexClass_Name__c = queueUpdateComponentFromSFDXJob.getJobInfo('ApexClassName'),
                        AsyncApexJob_Id__c = jobId,
                        AsyncApexJob_Name__c = queueUpdateComponentFromSFDXJob.getJobInfo('jobName'),
                        AsyncApexJob_Status__c = 'Queued',
                        Send_Toast__c = false
                    ));  
                }else{
                    jobIds.add(existingJobs[0].Id);

                    EventBus.publish(new CPM_Async_Event__e(
                        ApexClass_Name__c = queueUpdateComponentFromSFDXJob.getJobInfo('ApexClassName'),
                        AsyncApexJob_Id__c = existingJobs[0].Id,
                        AsyncApexJob_Name__c = queueUpdateComponentFromSFDXJob.getJobInfo('jobName'),
                        AsyncApexJob_Status__c = 'Processing',
                        Send_Toast__c = false
                    ));  
                }
            }

            if(demoComponent[0].Source_Install_Type_Flag__c){
                QueueUpdateComponentSourceCommitInfo queueUpdateComponentSourceCommitInfoJob = new QueueUpdateComponentSourceCommitInfo(demoComponentId, new Map<String,String>{});   
                List<AsyncApexJob> existingJobs = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE Status IN ('Holding','Queued','Preparing','Processing') AND ApexClass.Name = :queueUpdateComponentSourceCommitInfoJob.getJobInfo('ApexClassName') LIMIT 1];
                if (existingJobs.size() == 0){
                    jobId = System.enqueueJob(queueUpdateComponentSourceCommitInfoJob);
                    jobIds.add(jobId);    
                    
                    EventBus.publish(new CPM_Async_Event__e(
                        ApexClass_Name__c = queueUpdateComponentSourceCommitInfoJob.getJobInfo('ApexClassName'),
                        AsyncApexJob_Id__c = jobId,
                        AsyncApexJob_Name__c = queueUpdateComponentSourceCommitInfoJob.getJobInfo('jobName'),
                        AsyncApexJob_Status__c = 'Queued',
                        Send_Toast__c = false
                    ));  

                    jobIds.add(jobId); 
                }else{
                    jobIds.add(existingJobs[0].Id);

                    EventBus.publish(new CPM_Async_Event__e(
                        ApexClass_Name__c = queueUpdateComponentSourceCommitInfoJob.getJobInfo('ApexClassName'),
                        AsyncApexJob_Id__c = existingJobs[0].Id,
                        AsyncApexJob_Name__c = queueUpdateComponentSourceCommitInfoJob.getJobInfo('jobName'),
                        AsyncApexJob_Status__c = 'Processing',
                        Send_Toast__c = false
                    ));                      
                }
                
                QueueUpdateComponentSourceTagInfo queueUpdateComponentSourceTagInfoJob = new QueueUpdateComponentSourceTagInfo(demoComponentId); 
                existingJobs = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE Status IN ('Holding','Queued','Preparing','Processing') AND ApexClass.Name = :queueUpdateComponentSourceTagInfoJob.getJobInfo('ApexClassName') LIMIT 1];
                if (existingJobs.size() == 0){
                    jobId = System.enqueueJob(queueUpdateComponentSourceTagInfoJob);
                    jobIds.add(jobId);    

                    EventBus.publish(new CPM_Async_Event__e(
                        ApexClass_Name__c = queueUpdateComponentSourceTagInfoJob.getJobInfo('ApexClassName'),
                        AsyncApexJob_Id__c = jobId,
                        AsyncApexJob_Name__c = queueUpdateComponentSourceTagInfoJob.getJobInfo('jobName'),
                        AsyncApexJob_Status__c = 'Queued',
                        Send_Toast__c = false
                    ));  
                }else{
                    jobIds.add(existingJobs[0].Id);

                    EventBus.publish(new CPM_Async_Event__e(
                        ApexClass_Name__c = queueUpdateComponentSourceTagInfoJob.getJobInfo('ApexClassName'),
                        AsyncApexJob_Id__c = existingJobs[0].Id,
                        AsyncApexJob_Name__c = queueUpdateComponentSourceTagInfoJob.getJobInfo('jobName'),
                        AsyncApexJob_Status__c = 'Processing',
                        Send_Toast__c = false
                    ));   
                }
            }
    
        }

        return jobIds;
    }
}