force-app/main/default/objects/CPM_Async_Event__e/CPM_Async_Event__e.object-meta.xml
<CustomObject>
    <label>CPM Async Event</label>
    <pluralLabel>CPM Async Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPM_Async_Event__e/fields/Demo_Component_Id__c.field-meta.xml
<CustomField>
    <fullName>Demo_Component_Id__c</fullName>
    <label>Demo Component Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Component_Update__e/CPM_Component_Update__e.object-meta.xml
<CustomObject>
    <description>Event signifying a change to an event that should be reflected in the front end interface.</description>
    <label>CPM Component Update</label>
    <pluralLabel>CPM Component Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPM_Component_Update__e/fields/Demo_Component_Id__c.field-meta.xml
<CustomField>
    <fullName>Demo_Component_Id__c</fullName>
    <label>Demo Component Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Component_Update__e/fields/Demo_Component_JSON__c.field-meta.xml
<CustomField>
    <fullName>Demo_Component_JSON__c</fullName>
    <label>Demo Component JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CPM_Component_Update__e/fields/Insert_Flag__c.field-meta.xml
<CustomField>
    <fullName>Insert_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Demo Component Was Inserted</description>
    <label>Insert Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPM_Component_Update__e/fields/Update_Flag__c.field-meta.xml
<CustomField>
    <fullName>Update_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Demo Component Was Updated</description>
    <label>Update Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QueueComponentUpdateEventHelper.cls
public with sharing class QueueComponentUpdateEventHelper {
    public static final String FLAG_TRUE = 'true';
    public static final String FLAG_FALSE = 'false';

    public static final String FIELD_DELETE_FLAG = 'Delete_Flag__c'; 
    public static final String FIELD_DEMO_COMPONENT_ID = 'Demo_Component_Id__c'; 
    public static final String FIELD_DEMO_COMPONENT_JSON = 'Demo_Component_JSON__c';
    public static final String FIELD_INSERT_FLAG = 'Insert_Flag__c';
    public static final String FIELD_UPDATE_FLAG = 'Update_Flag__c';

    @future (callout = true )
    public static void publishAsyncPlatformEvent(Map<String,String> eventInfo)
    {
        publish(eventInfo);
    }
    
    public static void publishPlatformEvent(Map<String,String> eventInfo)
    {
        publish(eventInfo);
    }

    private static void publish(Map<String, String> eventInfo){
        
        Boolean deleteFlag = False;
        Boolean insertFlag = False;
        Boolean updateFlag = False;

        if(eventInfo.containsKey(FIELD_DELETE_FLAG)){
            deleteFlag = eventInfo.get(FIELD_DELETE_FLAG) == FLAG_TRUE ? True : False;
        }

        if(eventInfo.containsKey(FIELD_INSERT_FLAG)){
            insertFlag = eventInfo.get(FIELD_INSERT_FLAG) == FLAG_TRUE ? True : False;
        }

        if(eventInfo.containsKey(FIELD_UPDATE_FLAG)){
            updateFlag = eventInfo.get(FIELD_UPDATE_FLAG) == FLAG_TRUE ? True : False;
        }

        EventBus.publish(new CPM_Component_Update__e(
            Demo_Component_Id__c = eventInfo.get(FIELD_DEMO_COMPONENT_ID), 
            Delete_Flag__c = deleteFlag, 
            Insert_Flag__c = insertFlag,
            Update_Flag__c = updateFlag,
            Demo_Component_JSON__c = eventInfo.containsKey(FIELD_DEMO_COMPONENT_JSON) ? eventInfo.get(FIELD_DEMO_COMPONENT_JSON) : ''));
    }

    public static String generateId() {

        Integer len = 16;
        Blob blobKey = crypto.generateAesKey(128);
        String key = EncodingUtil.convertToHex(blobKey);
        return key.substring(0,len);

        /*
        Integer s_num = 1;
            String result = String.valueOf(s_num++);
            return CPM_Async_Event__e.SObjectType.getDescribe().getKeyPrefix() + 
                '0'.repeat(12-result.length()) + result;
        */
    }
    
}