force-app/main/default/objects/CPM_Async_Event__e/CPM_Async_Event__e.object-meta.xml
<CustomObject>
    <label>CPM Async Event</label>
    <pluralLabel>CPM Async Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPM_Async_Event__e/fields/ApexClass_Name__c.field-meta.xml
<CustomField>
    <fullName>ApexClass_Name__c</fullName>
    <label>ApexClass Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Id__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Id__c</fullName>
    <label>AsyncApexJob Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Name__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Name__c</fullName>
    <label>AsyncApexJob Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Status__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Status__c</fullName>
    <description>Queued, Processing, Completed, Completed with Warnings, Completed with Errors, Failed</description>
    <label>AsyncApexJob Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/Send_Toast__c.field-meta.xml
<CustomField>
    <fullName>Send_Toast__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send toast to UI</description>
    <label>Send_Toast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CpmComponentInstallCheckerController.cls
public with sharing class CpmComponentInstallCheckerController {
    @AuraEnabled
    public String recordId { get; set; }

    @AuraEnabled
    public static List<ID> runApex(String searchKey){ 
        System.debug('Running CPMInstallCheckerController.runApex');
        List<ID> JobIDs = new List<ID>();

        List<AsyncApexJob> existingJobs = [SELECT Id, ApexClass.Name, Status FROM AsyncApexJob WHERE Status IN ('Holding','Queued','Preparing','Processing') AND ApexClass.Name = 'QueueGetInstalledPackages' LIMIT 1];
        if (existingJobs.size() == 0){
            QueueGetInstalledPackages updateJob = new QueueGetInstalledPackages();
            JobIDs.add(System.enqueueJob(updateJob));

            EventBus.publish(new CPM_Async_Event__e(
                ApexClass_Name__c = QueueGetInstalledPackages.class.getName(),
                AsyncApexJob_Id__c = JobIDs[0],
                AsyncApexJob_Name__c = updateJob.getJobName(),
                AsyncApexJob_Status__c = 'Queued',
                Send_Toast__c = false
            ));  
        }else{
            JobIDs.add(existingJobs[0].Id);
        }
    
        doLater();

        return JobIDs;
    }

    @future(callout=true)
    public static void doLater(){
        VersionHelper.updateComponentFromXTag();
    }
}