force-app/main/default/objects/CPM_Async_Event__e/CPM_Async_Event__e.object-meta.xml
<CustomObject>
    <label>CPM Async Event</label>
    <pluralLabel>CPM Async Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPM_Async_Event__e/fields/ApexClass_Name__c.field-meta.xml
<CustomField>
    <fullName>ApexClass_Name__c</fullName>
    <label>ApexClass Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Id__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Id__c</fullName>
    <label>AsyncApexJob Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Name__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Name__c</fullName>
    <label>AsyncApexJob Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Parent_Id__c</fullName>
    <label>AsyncApexJob Parent Id</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/AsyncApexJob_Status__c.field-meta.xml
<CustomField>
    <fullName>AsyncApexJob_Status__c</fullName>
    <description>Queued, Processing, Completed, Completed with Warnings, Completed with Errors, Failed</description>
    <label>AsyncApexJob Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/Send_Toast__c.field-meta.xml
<CustomField>
    <fullName>Send_Toast__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send toast to UI</description>
    <label>Send_Toast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/Toast_Message__c.field-meta.xml
<CustomField>
    <fullName>Toast_Message__c</fullName>
    <description>(Required) A string representing the body of the message. It can contain placeholders in the form of {0} ... {N}. The placeholders are replaced with the links on messageData.</description>
    <label>Toast Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/Toast_Mode__c.field-meta.xml
<CustomField>
    <fullName>Toast_Mode__c</fullName>
    <description>Determines how persistent the toast is. Valid values are: dismissable (default), remains visible until you click the close button or 3 seconds has elapsed, whichever comes first; pester, remains visible for 3 seconds and disappears automatically. No close button is provided; sticky, remains visible until you click the close button.</description>
    <label>Toast Mode</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/Toast_Title__c.field-meta.xml
<CustomField>
    <fullName>Toast_Title__c</fullName>
    <label>Toast Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPM_Async_Event__e/fields/Toast_Variant__c.field-meta.xml
<CustomField>
    <fullName>Toast_Variant__c</fullName>
    <description>Changes the appearance of the notice. Toasts inherit styling from toasts in the Lightning Design System. Valid values are: info (default), success, warning, and error.</description>
    <label>Toast Variant</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QueuePlatformEventHelper.cls
public with sharing class QueuePlatformEventHelper
{
	@future (callout = true )
	public static void publishAsyncPlatformEvent(Map<String,String> jobInfo, String status)
	{
        publish(jobInfo, status, null);
    }
    
	@future (callout = true )
	public static void publishAsyncPlatformEvent(Map<String,String> jobInfo, String status, Map<String,String> toastInfo)
	{
        publish(jobInfo, status, toastInfo);
    }
    
	public static void publishPlatformEvent(Map<String,String> jobInfo, String status)
	{
        publish(jobInfo, status, null);
    }
    
	public static void publishPlatformEvent(Map<String, String> jobInfo, String status, Map<String,String> toastInfo)
	{
        publish(jobInfo, status, toastInfo);
    }

    private static void publish(Map<String, String> jobInfo, String status, Map<String,String> toastInfo){

        if(null == toastInfo){
            toastInfo = new Map<String,String>{'Send_Toast__c' => 'false'};
        }

		EventBus.publish(new CPM_Async_Event__e(
            ApexClass_Name__c = jobInfo.get('ApexClassName'), 
            AsyncApexJob_Id__c = jobInfo.get('jobId'), 
            AsyncApexJob_Parent_Id__c = jobInfo.containsKey('parentJobId') ? jobInfo.get('parentJobId') : null, 
            AsyncApexJob_Name__c = jobInfo.get('jobName'), 
            AsyncApexJob_Status__c = status, 
            Send_Toast__c = true, 
            Toast_Title__c = toastInfo.containsKey('Toast_Title__c') ? toastInfo.get('Toast_Title__c') : null, 
            Toast_Message__c = toastInfo.containsKey('Toast_Message__c') ? toastInfo.get('Toast_Message__c') : null, 
            Toast_Variant__c = toastInfo.containsKey('Toast_Variant__c') ? toastInfo.get('Toast_Variant__c') : null, 
            Toast_Mode__c = toastInfo.containsKey('Toast_Mode__c') ? toastInfo.get('Toast_Mode__c') : null));
    }
    
}