force-app/main/default/objects/Component_Dependency__c/Component_Dependency__c.object-meta.xml
<CustomObject>
    <label>Component Dependency</label>
    <nameField>
        <displayFormat>GPBUMPD-{0000}</displayFormat>
        <label>Component Dependency Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Dependencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Dependency__c/fields/Demo_Component__c.field-meta.xml
<CustomField>
    <fullName>Demo_Component__c</fullName>
    <label>Demo Component</label>
    <referenceTo>Demo_Component__c</referenceTo>
    <relationshipLabel>Component Dependencies</relationshipLabel>
    <relationshipName>Component_Dependencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Component_Dependency__c/fields/Dependent_Component__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dependent Component</label>
    <referenceTo>Demo_Component__c</referenceTo>
    <relationshipLabel>Demo Components Depending on This</relationshipLabel>
    <relationshipName>Components_Depending_On</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Dependency__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <formula>IF(Dependent_Component__r.Installed__c = true, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Install_Key__c.field-meta.xml
<CustomField>
    <fullName>Install_Key__c</fullName>
    <description>The key needed to install the package.  You will be prompted for this after clicking the install link.</description>
    <inlineHelpText>The key needed to install the package.  You will be prompted for this after clicking the install link.</inlineHelpText>
    <label>Install Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Install_Url__c.field-meta.xml
<CustomField>
    <fullName>Package_Install_Url__c</fullName>
    <formula>IF(Package_Install_Type_Flag__c,&apos;/packagingSetupUI/ipLanding.app?apvId=&apos; + Latest_Subscriber_Package_Version_Id__c, &apos;N/A&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Package Install Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Url__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Url__c</fullName>
    <formula>IF(Source_Install_Type_Flag__c,&apos;https://hosted-scratch.herokuapp.com/byoo?template=&apos; + Github_Repository_URL__c, &apos;N/A&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Install Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CpmComponentInstallerController.cls
public with sharing class CpmComponentInstallerController {
    @AuraEnabled
    public String recordId { get; set; }

    @AuraEnabled(cacheable=true)
    public static list<Demo_Component__c> getDependentPackages(String searchKey){
        List<Component_Dependency__c> packageDependencies = new List<Component_Dependency__c>([SELECT Dependent_Component__c FROM Component_Dependency__c WHERE Demo_Component__c = :searchKey ]);
        Set<Id> Ids = new Set<Id>();
        for(Component_Dependency__c packageDependency:packageDependencies){
            Ids.add(packageDependency.Dependent_Component__c);
        }   
        List<Demo_Component__c> dependentPackages = new List<Demo_Component__c>([SELECT Id, Installed__c, Title__c, Source_Install_Type_Flag__c, Package_Install_Type_Flag__c, Github_Repository_URL__c, Latest_Subscriber_Package_Version_Id__c, Install_Key__c, Source_Install_Url__c, Package_Install_Url__c FROM Demo_Component__c WHERE Id in :Ids]);
        system.debug('found the following packages');
        system.debug(dependentPackages);
        return dependentPackages;
    }

}