force-app/main/default/objects/Component_Dependency__c/Component_Dependency__c.object-meta.xml
<CustomObject>
    <label>Component Dependency</label>
    <nameField>
        <displayFormat>GPBUMPD-{0000}</displayFormat>
        <label>Component Dependency Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Dependencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Dependency__c/fields/Demo_Component__c.field-meta.xml
<CustomField>
    <fullName>Demo_Component__c</fullName>
    <label>Demo Component</label>
    <referenceTo>Demo_Component__c</referenceTo>
    <relationshipLabel>Component Dependencies</relationshipLabel>
    <relationshipName>Component_Dependencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Component_Dependency__c/fields/Dependent_Component__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Component__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dependent Component</label>
    <referenceTo>Demo_Component__c</referenceTo>
    <relationshipLabel>Demo Components Depending on This</relationshipLabel>
    <relationshipName>Components_Depending_On</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Dependency__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <formula>IF(Dependent_Component__r.Installed__c = true, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A short description of the demo</description>
    <inlineHelpText>A short description of the demo</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this Package Installed</description>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Installed_Version_Tracking_Method__c.field-meta.xml
<CustomField>
    <fullName>Installed_Version_Tracking_Method__c</fullName>
    <label>Installed Version Tracking Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Github_Commit</fullName>
                <label>Github Commit</label>
            </value>
            <value>
                <fullName>Github Tag</fullName>
            </value>
            <value>
                <fullName>SFDX Project</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Subscriber_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Subscriber_Version_Id__c</fullName>
    <label>Package Installed Subscriber Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Version_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Version_Name__c</fullName>
    <description>Name of the Installed Component (When Installed via Source)</description>
    <label>Package Installed Version Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Installed_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Package_Installed_Version_Number__c</fullName>
    <label>Package Installed Version Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Name__c</fullName>
    <description>Name of the Package. Can be sourced by sfdx-project.json or tooling api.</description>
    <label>Package Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueueProcessDependentPackages.cls
public class QueueProcessDependentPackages implements Queueable, Database.AllowsCallouts {
    /*************STANDARD HELPER VARIABLES / FUNCTIONS*************/
    Map<String,String> jobInfo = new Map<String,String>{
        QueuePlatformAsyncEventHelper.FIELD_JOB_NAME =>  'Checking for installed Salesforce Packages', 
        QueuePlatformAsyncEventHelper.FIELD_APEX_CLASS_NAME => QueueProcessDependentPackages.class.getName()
    };

    public Map<String,String> GetJobInfo() {
        return this.jobInfo;
    }    

    public String GetJobInfo(String key) {
        return this.jobInfo.get(key);
    }

    public void SetJobInfo(String key, String value) {
        this.jobInfo.put(key, value);
    }

    public void SetJobStage(String value) {
        this.jobInfo.put(QueuePlatformAsyncEventHelper.FIELD_CURRENT_JOB_STAGE, value);  
    }   

    /*************QUEUEABLE SPECIFIC VARIABLES / FUNCTIONS*************/
    String parentDemoComponentId;
    List<String> dependentPackageVersionIds = new List<String>();


    /*************CONSTRUCTORS*************/
    public QueueProcessDependentPackages(String parentDemoComponentId, List<String> dependentPackageVersionIds) {
        this.SetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_ID, QueuePlatformAsyncEventHelper.generateId()); 
        this.SetJobStage(QueuePlatformAsyncEventHelper.STAGE_QUEUED); 
        QueuePlatformAsyncEventHelper.publishPlatformEvent(this.GetJobInfo());
        system.debug(this.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_APEX_CLASS_NAME)+' has been Queued');  
    }

    public QueueProcessDependentPackages(String parentJobId, String parentDemoComponentId, List<String> dependentPackageVersionIds) {
        this.SetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_ID, QueuePlatformAsyncEventHelper.generateId()); 
        this.SetJobStage(QueuePlatformAsyncEventHelper.STAGE_QUEUED); 
        this.SetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID, parentJobId);  
        QueuePlatformAsyncEventHelper.publishPlatformEvent(this.GetJobInfo());
        system.debug(this.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_APEX_CLASS_NAME)+' has been Queued');  

        this.parentDemoComponentId = parentDemoComponentId;
        this.dependentPackageVersionIds = dependentPackageVersionIds;
    }

    /*************EXECUTE METHOD*************/   
    public void execute(QueueableContext context) {
    /*************STANDARD EXECUTE STARTER*************/
    this.SetJobStage(QueuePlatformAsyncEventHelper.STAGE_PROCESSING);
    QueuePlatformAsyncEventHelper.publishPlatformEvent(this.GetJobInfo());
    system.debug(this.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_APEX_CLASS_NAME)+' has been is now processing');  

    doLater(this.jobInfo, this.parentDemoComponentId, this.dependentPackageVersionIds);
    }

    @future(callout=true)
    private static void doLater(Map<String, String> jobInfo, String parentDemoComponentId, List<String> dependentPackageVersionIds) {
        system.debug(jobInfo.get(QueuePlatformAsyncEventHelper.FIELD_APEX_CLASS_NAME)+' is now processing doLater');  

        List<MetadataInstalledPackageResponseRecord> metadataInstalledPackageResponseRecords = new List<MetadataInstalledPackageResponseRecord>();
        List<Demo_Component__c> parentDemoComponentLookup = [SELECT Id from Demo_Component__c WHERE Id = :parentDemoComponentId];
        //TODO: Add Logic to check to see if Parent Demo Component Exists....
        Demo_Component__c parentDemoComponent = parentDemoComponentLookup[0];

        for(String dependentPackageVersionId: dependentPackageVersionIds){
            MetadataInstalledPackageResponseRecord metadataInstalledPackageResponseRecord = new MetadataInstalledPackageResponseRecord();
            MetadataSubscriberPackageVersion metadataSubscriberPackageVersion = new MetadataSubscriberPackageVersion();
            MetadataSubscriberPackage metadataSubscriberPackage = new MetadataSubscriberPackage();

            metadataSubscriberPackageVersion = MetadataAPIHelper.getSubscriberPackageVersion(dependentPackageVersionId);
            if (metadataSubscriberPackageVersion != null) {
                System.debug('Successfully found Subscriber Package Version Info from Tooling API');
                metadataSubscriberPackage = MetadataAPIHelper.getSubscriberPackage(metadataSubscriberPackageVersion.subscriberPackageId);
                if (metadataSubscriberPackage != null) {
                    System.debug('Successfully found Subscriber Package Info from Tooling API');
                    metadataInstalledPackageResponseRecord.subscriberPackageId = dependentPackageVersionId;
                    metadataInstalledPackageResponseRecord.subscriberpackage = metadataSubscriberPackage;
                    metadataInstalledPackageResponseRecord.subscriberPackageVersion = metadataSubscriberPackageVersion;
                    metadataInstalledPackageResponseRecords.add(metadataInstalledPackageResponseRecord);
                }else{
                    System.debug('Could not find Subscriber Package Version Info from Tooling API');
                }
            }else{
                System.debug('Could not find Subscriber Package Version Info from Tooling API');
            }
        }


        for(MetadataInstalledPackageResponseRecord metadataInstalledPackageResponseRecord: metadataInstalledPackageResponseRecords){
            Demo_Component__c demoComponent = new Demo_Component__c();
            List<Demo_Component__c> demoComponentLookup = [
                SELECT
                Id,
                Latest_Subscriber_Package_Version_Id__c,
                Title__c,
                Installed__c,
                Package_Installed_Subscriber_Version_Id__c,
                Subscriber_Package_Id__c,
                Package_Install_Type_Flag__c,
                SFDX_Package_Enabled_Flag__c
                FROM Demo_Component__c
                WHERE
                Subscriber_Package_Id__c = :metadataInstalledPackageResponseRecord.subscriberPackage.Id
                LIMIT 1
            ];
            
            MetadataSubscriberPackageVersion subscriberPackageVersion = metadataInstalledPackageResponseRecord.subscriberPackageVersion;
            MetadataSubscriberPackage subscriberpackage = metadataInstalledPackageResponseRecord.subscriberpackage;

            //TODO:GET INSTALL DATE FROM METADATA API.....

            if(demoComponentLookup.size() == 0){
                System.debug('Demo_Component__c Did not previously exist, updating');

                System.debug('No Demo Component found for ' + metadataInstalledPackageResponseRecord.subscriberPackage.name + ' installed package, creating a new one...');
                demoComponent.Package_Install_Type_Flag__c = true;
                demoComponent.Title__c = subscriberPackage.name;
                demoComponent.Description__c = subscriberPackage.description;
                demoComponent.Package_Installed_Subscriber_Version_Id__c = subscriberPackageVersion.id;
                demoComponent.Package_Installed_Version_Name__c = subscriberPackageVersion.name;
                demoComponent.Package_Installed_Version_Number__c = subscriberPackageVersion.getSubscriberPackageVersionNumberText();
                demoComponent.Installation_Type__c = 'Package';
                demoComponent.Installed_Version_Tracking_Method__c = 'None';

                demoComponent.Subscriber_Package_Id__c = subscriberPackage.id;
                demoComponent.Package_Name__c = subscriberPackage.name;
                demoComponent.Latest_Subscriber_Package_Version_Id__c = subscriberPackageVersion.id;
                demoComponent.Latest_Package_Version__c = subscriberPackageVersion.getSubscriberPackageVersionNumberText();
                demoComponent.Latest_Package_Version_Name__c = subscriberPackageVersion.name;
                demoComponent.Last_Fetched__c = Datetime.Now();

                insert demoComponent;

                jobInfo.put(QueuePlatformAsyncEventHelper.FIELD_CURRENT_JOB_STAGE, QueuePlatformAsyncEventHelper.STAGE_COMPLETED);
                QueuePlatformAsyncEventHelper.publishPlatformEvent(jobInfo,new Map<String,String>{
                    QueuePlatformAsyncEventHelper.FIELD_EVENT_STATUS_TITLE => 'Job Update Notification',
                    QueuePlatformAsyncEventHelper.FIELD_EVENT_STATUS_MESSAGE => 'Created new Demo Component named , "' + demoComponent.Title__c +'" That is a dependency of another package',
                    QueuePlatformAsyncEventHelper.FIELD_EVENT_LEVEL => QueuePlatformAsyncEventHelper.EVENT_LEVEL_SUCCESS
                });  

                QueueComponentUpdateEventHelper.publishPlatformEvent(new Map<String,String>{
                    QueueComponentUpdateEventHelper.FIELD_UPDATE_FLAG => QueueComponentUpdateEventHelper.FLAG_TRUE,
                    QueueComponentUpdateEventHelper.FIELD_DEMO_COMPONENT_ID => demoComponent.Id
                });
            }else{
                demoComponent = demoComponentLookup[0];
            }

                //Look for existing demo component dependency...
            List<Component_Dependency__c> dependentComponentLookup = [SELECT Id FROM Component_Dependency__c WHERE Demo_Component__c =:parentDemoComponent.Id AND Dependent_Component__c =:demoComponent.Id];
            if(dependentComponentLookup.size() == 0){
                System.debug('Component Dependency Not found, Creating New record');
                insert new Component_Dependency__c(
                    Dependent_Component__c = demoComponent.Id,
                    Demo_Component__c = parentDemoComponent.Id
                );
            }else{
                System.debug('Existing Component Dependency ' + dependentComponentLookup[0].Id + ' Found, Ignoring.');
            }
        }

        jobInfo.put(QueuePlatformAsyncEventHelper.FIELD_CURRENT_JOB_STAGE, QueuePlatformAsyncEventHelper.STAGE_COMPLETED);
        QueuePlatformAsyncEventHelper.publishPlatformEvent(jobInfo);   
    }
}