force-app/main/default/objects/Component_Dependency__c/Component_Dependency__c.object-meta.xml
<CustomObject>
    <label>Component Dependency</label>
    <nameField>
        <displayFormat>GPBUMPD-{0000}</displayFormat>
        <label>Component Dependency Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Dependencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Dependency__c/fields/Demo_Component__c.field-meta.xml
<CustomField>
    <fullName>Demo_Component__c</fullName>
    <label>Demo Component</label>
    <referenceTo>Demo_Component__c</referenceTo>
    <relationshipLabel>Component Dependencies</relationshipLabel>
    <relationshipName>Component_Dependencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/Demo_Component__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>Demo Component</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Component Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demo Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demo_Component__c/fields/Github_Repository_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository_URL__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Last_Fetched__c.field-meta.xml
<CustomField>
    <fullName>Last_Fetched__c</fullName>
    <label>Last Fetched</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Latest_Subscriber_Package_Version_Id__c.field-meta.xml
<CustomField>
    <fullName>Latest_Subscriber_Package_Version_Id__c</fullName>
    <description>For Packages, the latest Subscriber Package Version ID</description>
    <label>Latest Subscriber Package Version Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Package_Name__c</fullName>
    <description>Name of the Package. Can be sourced by sfdx-project.json or tooling api.</description>
    <label>Package Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/SFDX_Package_Enabled_Flag__c.field-meta.xml
<CustomField>
    <fullName>SFDX_Package_Enabled_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an SFDX Project that leverages Packages for versioning</description>
    <label>SFDX Package Enabled Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Source_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Type_Flag__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is a Generation 1 Project leveraging a source folder and project.XML, it can deployed on an org as source code.</description>
    <label>Source Install Type Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demo_Component__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The title of the demo</description>
    <inlineHelpText>The title of the demo</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QueueProcessDependentPackagesTest.cls
@isTest
public with sharing class QueueProcessDependentPackagesTest {

    @testSetup 
    static void setup() {
        Demo_Component__c demoComponent = new Demo_Component__c(
            Github_Repository_URL__c = ApiCalloutMock.VM_GITHUB_REPO_URL,
            SFDX_Package_Enabled_Flag__c=true,
            Source_Install_Type_Flag__c=true,
            Package_Install_Type_Flag__c=true,
            Title__c = 'Visitor Management Demo Scenario',
            Package_Name__c = 'Visitor Management Demo Scenario',
            Latest_Package_Version_Name__c = '',
            Latest_Package_Version__c = '0.1.1-1',
            Subscriber_Package_Id__c = ApiCalloutMock.SUBSCRIBER_PACKAGE_ID,
            Latest_Subscriber_Package_Version_Id__c = '',
            Last_Fetched__c = datetime.now(),
            Update_Available__c = false
        );
        insert demoComponent;
    }
    
    static testmethod void testJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 
        List<String> dependentPackageVersionIds = new List<String>{ApiCalloutMock.PACKAGE_DEPENDENCY_1_SUBSCRIBER_PACKAGE_VERSION_ID, ApiCalloutMock.PACKAGE_DEPENDENCY_2_SUBSCRIBER_PACKAGE_VERSION_ID};

        Demo_Component__c demoComponent = [SELECT Id FROM Demo_Component__c where Subscriber_Package_Id__c =:ApiCalloutMock.SUBSCRIBER_PACKAGE_ID LIMIT 1];


        QueueProcessDependentPackages queueProcessDependentPackagesJob = new QueueProcessDependentPackages(String.valueOf(demoComponent.Id),dependentPackageVersionIds);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueProcessDependentPackagesJob);
        QueueProcessDependentPackages.doLater(queueProcessDependentPackagesJob.GetJobInfo(), String.valueOf(demoComponent.Id), dependentPackageVersionIds);
        Test.stopTest(); 
        
        List<Demo_Component__C> demoComponents = [SELECT Id FROM Demo_Component__c];

        List<Component_Dependency__c> dependentComponents = [SELECT Id FROM Component_Dependency__c where Demo_Component__c = :demoComponent.Id];
        
        AsyncApexJob jobInfo = [SELECT Id, Status, NumberOfErrors FROM AsyncApexJob WHERE Id = :jobId LIMIT 1];

        System.assertEquals(2, dependentComponents.size());
        System.assertEquals(3, demoComponents.size());  
        System.assertEquals(jobId, jobInfo.Id);
    }


    static testmethod void testChildJob() {
        Test.setMock(HttpCalloutMock.class, new ApiCalloutMock()); 
        List<String> dependentPackageVersionIds = new List<String>{ApiCalloutMock.PACKAGE_DEPENDENCY_1_SUBSCRIBER_PACKAGE_VERSION_ID, ApiCalloutMock.PACKAGE_DEPENDENCY_2_SUBSCRIBER_PACKAGE_VERSION_ID};

        Demo_Component__c demoComponent = [SELECT Id FROM Demo_Component__c where Subscriber_Package_Id__c =:ApiCalloutMock.SUBSCRIBER_PACKAGE_ID LIMIT 1];

        String ParentJobId = QueuePlatformAsyncEventHelper.generateId();
        QueueProcessDependentPackages queueProcessDependentPackagesJob = new QueueProcessDependentPackages(ParentJobId, String.valueOf(demoComponent.Id), dependentPackageVersionIds);
        
        Test.startTest();        
        Id jobId = System.enqueueJob(queueProcessDependentPackagesJob);
        Test.stopTest(); 
        
        System.assertEquals(ParentJobId, queueProcessDependentPackagesJob.GetJobInfo(QueuePlatformAsyncEventHelper.FIELD_JOB_PARENT_ID));
    }

}