force-app/main/default/objects/Cpm_Client_Settings__c/fields/Last_Library_Refresh_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Library_Refresh_Date__c</fullName>
    <label>Last Library Refresh Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cpm_Client_Settings__c/fields/Sandbox_Flag__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the current environment is a sandbox</description>
    <label>Sandbox Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CpmClientCustomSettingHelperTest.cls
@isTest
public with sharing class CpmClientCustomSettingHelperTest {

    @testSetup 
    static void setup() {
    }
    
    static testmethod void testExistingCustomSetting() {
        List<Cpm_Client_Settings__c> appSettings = [SELECT Id, Last_Library_Refresh_Date__c, Initial_Config_Flag__c, Sandbox_Flag__c FROM Cpm_Client_Settings__c]; 
        
        Cpm_Client_Settings__c appSetting = new Cpm_Client_Settings__c();
        appSetting.Sandbox_Flag__c = true; 
        insert appSetting;

        Test.startTest();        
            Cpm_Client_Settings__c getAppSetting = CpmClientCustomSettingHelper.getAppSettings();
        Test.stopTest(); 

        System.assertEquals(0, appSettings.size());    
        System.assertEquals(true, getAppSetting.Sandbox_Flag__c); 
    }

    static testmethod void testNoExistingCustomSetting() {
        List<Cpm_Client_Settings__c> beforeTestAppSetting = [SELECT Id, Last_Library_Refresh_Date__c, Initial_Config_Flag__c, Sandbox_Flag__c FROM Cpm_Client_Settings__c]; 
       
        Test.startTest();        
            Cpm_Client_Settings__c getAppSetting = CpmClientCustomSettingHelper.getAppSettings();
        Test.stopTest(); 
  
        List<Cpm_Client_Settings__c> afterTestAppSetting = [SELECT Id, Last_Library_Refresh_Date__c, Initial_Config_Flag__c, Sandbox_Flag__c FROM Cpm_Client_Settings__c]; 
       
        System.assertEquals(0, beforeTestAppSetting.size()); 
        System.assertEquals(1, afterTestAppSetting.size());                
    }

}