force-app/main/default/objects/GPBU_Package__c/GPBU_Package__c.object-meta.xml
<CustomObject>
    <description>This object holds GPBU demo descriptions and install links.</description>
    <label>GPBU Package</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Package Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GPBU Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GPBU_Package__c/fields/Github_Repository__c.field-meta.xml
<CustomField>
    <fullName>Github_Repository__c</fullName>
    <description>If this package is sourced from a Github Repository, this is its URL.</description>
    <label>Github Repository</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPBU_Package__c/fields/Install_Key__c.field-meta.xml
<CustomField>
    <fullName>Install_Key__c</fullName>
    <defaultValue>&quot;gpbudemo&quot;</defaultValue>
    <description>The key needed to install the package.  You will be prompted for this after clicking the install link.</description>
    <inlineHelpText>The key needed to install the package.  You will be prompted for this after clicking the install link.</inlineHelpText>
    <label>Install Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPBU_Package__c/fields/Package_Install_Type_Flag__c.field-meta.xml
<CustomField>
    <fullName>Package_Install_Type_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Package may be installed as a Unlocked, Unmanaged, or Managed Package. Leverages a &quot;SubscriberPackageVersionId&quot;</description>
    <label>Package_Install_Type_Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GPBU_Package__c/fields/Source_Install_Url__c.field-meta.xml
<CustomField>
    <fullName>Source_Install_Url__c</fullName>
    <formula>IF(Source_Install_Type_Flag__c,&apos;https://hosted-scratch.herokuapp.com/byoo?template=&apos; + Github_Repository__c, &apos;N/A&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Install Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Package_Dependency__c/Package_Dependency__c.object-meta.xml
<CustomObject>
    <label>Package Dependency</label>
    <nameField>
        <displayFormat>GPBUMPD-{0000}</displayFormat>
        <label>Package Dependency Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Package Dependencies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package_Dependency__c/fields/Dependent_Package__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Package__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dependent Package</label>
    <referenceTo>GPBU_Package__c</referenceTo>
    <relationshipLabel>Packages Depending on This</relationshipLabel>
    <relationshipName>Packages_Depending_On</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package_Dependency__c/fields/GPBU_Package__c.field-meta.xml
<CustomField>
    <fullName>GPBU_Package__c</fullName>
    <label>GPBU Package</label>
    <referenceTo>GPBU_Package__c</referenceTo>
    <relationshipLabel>Package Dependencies</relationshipLabel>
    <relationshipName>Package_Dependencies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Package_Dependency__c/fields/Installed__c.field-meta.xml
<CustomField>
    <fullName>Installed__c</fullName>
    <formula>IF(Dependent_Package__r.Installed__c = true, true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PackageInstallerController.cls
public with sharing class PackageInstallerController {
    @AuraEnabled
    public String recordId { get; set; }

    @AuraEnabled(cacheable=true)
    public static list<GPBU_Package__c> getDependentPackages(String searchKey){
        List<Package_Dependency__c> packageDependencies = new List<Package_Dependency__c>([SELECT Dependent_Package__c FROM Package_Dependency__c WHERE GPBU_Package__c = :searchKey ]);
        Set<Id> Ids = new Set<Id>();
        for(Package_Dependency__c packageDependency:packageDependencies){
            Ids.add(packageDependency.Dependent_Package__c);
        }   
        List<GPBU_Package__c> dependentPackages = new List<GPBU_Package__c>([SELECT Id, Installed__c, Title__c, Source_Install_Type_Flag__c, Package_Install_Type_Flag__c, Github_Repository__c, Latest_Subscriber_Package_Version_Id__c, Install_Key__c, Source_Install_Url__c, Package_Install_Url__c FROM GPBU_Package__c WHERE Id in :Ids]);
        system.debug('found the following packages');
        system.debug(dependentPackages);
        return dependentPackages;
    }

}